/** This software is released under the University of Illinois/Research and Academic Use License. See
  * the LICENSE file in the root folder for details. Copyright (c) 2016
  *
  * Developed by: The Cognitive Computations Group, University of Illinois at Urbana-Champaign
  * http://cogcomp.cs.illinois.edu/
  */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.30 at 10:59:22 AM CET 
//


package edu.illinois.cs.cogcomp.saulexamples.nlp.SpatialRoleLabeling.SpRL2013;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the be.liir.SpRL2013Document.jaxb package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: be.liir.SpRL2013Document.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DIRECTION }
     * 
     */
    public DIRECTION createDIRECTION() {
        return new DIRECTION();
    }

    /**
     * Create an instance of {@link DISTANCE }
     * 
     */
    public DISTANCE createDISTANCE() {
        return new DISTANCE();
    }

    /**
     * Create an instance of {@link LANDMARK }
     * 
     */
    public LANDMARK createLANDMARK() {
        return new LANDMARK();
    }

    /**
     * Create an instance of {@link SpRL2013Document }
     * 
     */
    public SpRL2013Document createSpRL() {
        return new SpRL2013Document();
    }

    /**
     * Create an instance of {@link URL }
     * 
     */
    public URL createURL() {
        return new URL();
    }

    /**
     * Create an instance of {@link CP }
     * 
     */
    public CP createCP() {
        return new CP();
    }

    /**
     * Create an instance of {@link TEXT }
     * 
     */
    public TEXT createTEXT() {
        return new TEXT();
    }

    /**
     * Create an instance of {@link TAGS }
     * 
     */
    public TAGS createTAGS() {
        return new TAGS();
    }

    /**
     * Create an instance of {@link TRAJECTOR }
     * 
     */
    public TRAJECTOR createTRAJECTOR() {
        return new TRAJECTOR();
    }

    /**
     * Create an instance of {@link SPATIALINDICATOR }
     * 
     */
    public SPATIALINDICATOR createSPATIALINDICATOR() {
        return new SPATIALINDICATOR();
    }

    /**
     * Create an instance of {@link MOTIONINDICATOR }
     * 
     */
    public MOTIONINDICATOR createMOTIONINDICATOR() {
        return new MOTIONINDICATOR();
    }

    /**
     * Create an instance of {@link PATH }
     * 
     */
    public PATH createPATH() {
        return new PATH();
    }

    /**
     * Create an instance of {@link RELATION }
     * 
     */
    public RELATION createRELATION() {
        return new RELATION();
    }


}
