/** This software is released under the University of Illinois/Research and Academic Use License. See
  * the LICENSE file in the root folder for details. Copyright (c) 2016
  *
  * Developed by: The Cognitive Computations Group, University of Illinois at Urbana-Champaign
  * http://cogcomp.cs.illinois.edu/
  */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.25 at 08:20:43 PM IRDT 
//


package edu.illinois.cs.cogcomp.saulexamples.nlp.SpatialRoleLabeling.SpRL2015;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TEXT_QNAME = new QName("", "TEXT");
    private final static QName _CP_QNAME = new QName("", "CP");
    private final static QName _URL_QNAME = new QName("", "URL");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PATH }
     * 
     */
    public PATH createPATH() {
        return new PATH();
    }

    /**
     * Create an instance of {@link SPATIALSIGNAL }
     * 
     */
    public SPATIALSIGNAL createSPATIALSIGNAL() {
        return new SPATIALSIGNAL();
    }

    /**
     * Create an instance of {@link MEASURE }
     * 
     */
    public MEASURE createMEASURE() {
        return new MEASURE();
    }

    /**
     * Create an instance of {@link METALINK }
     * 
     */
    public METALINK createMETALINK() {
        return new METALINK();
    }

    /**
     * Create an instance of {@link PLACE }
     * 
     */
    public PLACE createPLACE() {
        return new PLACE();
    }

    /**
     * Create an instance of {@link QSLINK }
     * 
     */
    public QSLINK createQSLINK() {
        return new QSLINK();
    }

    /**
     * Create an instance of {@link MOTION }
     * 
     */
    public MOTION createMOTION() {
        return new MOTION();
    }

    /**
     * Create an instance of {@link NONMOTIONEVENT }
     * 
     */
    public NONMOTIONEVENT createNONMOTIONEVENT() {
        return new NONMOTIONEVENT();
    }

    /**
     * Create an instance of {@link SpRL2015Document }
     * 
     */
    public SpRL2015Document createSpaceEvalTaskv12() {
        return new SpRL2015Document();
    }

    /**
     * Create an instance of {@link TAGS }
     * 
     */
    public TAGS createTAGS() {
        return new TAGS();
    }

    /**
     * Create an instance of {@link SPATIALENTITY }
     * 
     */
    public SPATIALENTITY createSPATIALENTITY() {
        return new SPATIALENTITY();
    }

    /**
     * Create an instance of {@link MOTIONSIGNAL }
     * 
     */
    public MOTIONSIGNAL createMOTIONSIGNAL() {
        return new MOTIONSIGNAL();
    }

    /**
     * Create an instance of {@link OLINK }
     * 
     */
    public OLINK createOLINK() {
        return new OLINK();
    }

    /**
     * Create an instance of {@link MOVELINK }
     * 
     */
    public MOVELINK createMOVELINK() {
        return new MOVELINK();
    }

    /**
     * Create an instance of {@link MEASURELINK }
     * 
     */
    public MEASURELINK createMEASURELINK() {
        return new MEASURELINK();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEXT")
    public JAXBElement<String> createTEXT(String value) {
        return new JAXBElement<String>(_TEXT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CP")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCP(String value) {
        return new JAXBElement<String>(_CP_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "URL")
    public JAXBElement<String> createURL(String value) {
        return new JAXBElement<String>(_URL_QNAME, String.class, null, value);
    }

}
