/** This software is released under the University of Illinois/Research and Academic Use License. See
  * the LICENSE file in the root folder for details. Copyright (c) 2016
  *
  * Developed by: The Cognitive Computations Group, University of Illinois at Urbana-Champaign
  * http://cogcomp.cs.illinois.edu/
  */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.25 at 08:20:43 PM IRDT 
//


package edu.illinois.cs.cogcomp.saulexamples.nlp.SpatialRoleLabeling.SpRL2015;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "place",
    "path",
    "spatialentity",
    "nonmotionevent",
    "motion",
    "spatialsignal",
    "motionsignal",
    "measure",
    "qslink",
    "olink",
    "movelink",
    "measurelink",
    "metalink",
    "cp",
    "url"
})
@XmlRootElement(name = "TAGS")
public class TAGS {

    @XmlElement(name = "PLACE", required = true)
    protected List<PLACE> place;
    @XmlElement(name = "PATH")
    protected List<PATH> path;
    @XmlElement(name = "SPATIAL_ENTITY", required = true)
    protected List<SPATIALENTITY> spatialentity;
    @XmlElement(name = "NONMOTION_EVENT")
    protected List<NONMOTIONEVENT> nonmotionevent;
    @XmlElement(name = "MOTION", required = true)
    protected List<MOTION> motion;
    @XmlElement(name = "SPATIAL_SIGNAL")
    protected List<SPATIALSIGNAL> spatialsignal;
    @XmlElement(name = "MOTION_SIGNAL")
    protected List<MOTIONSIGNAL> motionsignal;
    @XmlElement(name = "MEASURE")
    protected List<MEASURE> measure;
    @XmlElement(name = "QSLINK")
    protected List<QSLINK> qslink;
    @XmlElement(name = "OLINK")
    protected List<OLINK> olink;
    @XmlElement(name = "MOVELINK")
    protected List<MOVELINK> movelink;
    @XmlElement(name = "MEASURELINK")
    protected List<MEASURELINK> measurelink;
    @XmlElement(name = "METALINK")
    protected List<METALINK> metalink;
    @XmlElement(name = "CP")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String cp;
    @XmlElement(name = "URL")
    @XmlSchemaType(name = "anyURI")
    protected String url;

    /**
     * Gets the value of the place property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the place property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPLACE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PLACE }
     * 
     * 
     */
    public List<PLACE> getPLACE() {
        if (place == null) {
            place = new ArrayList<PLACE>();
        }
        return this.place;
    }

    /**
     * Gets the value of the path property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the path property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPATH().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PATH }
     * 
     * 
     */
    public List<PATH> getPATH() {
        if (path == null) {
            path = new ArrayList<PATH>();
        }
        return this.path;
    }

    /**
     * Gets the value of the spatialentity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spatialentity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSPATIALENTITY().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SPATIALENTITY }
     * 
     * 
     */
    public List<SPATIALENTITY> getSPATIALENTITY() {
        if (spatialentity == null) {
            spatialentity = new ArrayList<SPATIALENTITY>();
        }
        return this.spatialentity;
    }

    /**
     * Gets the value of the nonmotionevent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nonmotionevent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNONMOTIONEVENT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NONMOTIONEVENT }
     * 
     * 
     */
    public List<NONMOTIONEVENT> getNONMOTIONEVENT() {
        if (nonmotionevent == null) {
            nonmotionevent = new ArrayList<NONMOTIONEVENT>();
        }
        return this.nonmotionevent;
    }

    /**
     * Gets the value of the motion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the motion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMOTION().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MOTION }
     * 
     * 
     */
    public List<MOTION> getMOTION() {
        if (motion == null) {
            motion = new ArrayList<MOTION>();
        }
        return this.motion;
    }

    /**
     * Gets the value of the spatialsignal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spatialsignal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSPATIALSIGNAL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SPATIALSIGNAL }
     * 
     * 
     */
    public List<SPATIALSIGNAL> getSPATIALSIGNAL() {
        if (spatialsignal == null) {
            spatialsignal = new ArrayList<SPATIALSIGNAL>();
        }
        return this.spatialsignal;
    }

    /**
     * Gets the value of the motionsignal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the motionsignal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMOTIONSIGNAL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MOTIONSIGNAL }
     * 
     * 
     */
    public List<MOTIONSIGNAL> getMOTIONSIGNAL() {
        if (motionsignal == null) {
            motionsignal = new ArrayList<MOTIONSIGNAL>();
        }
        return this.motionsignal;
    }

    /**
     * Gets the value of the measure property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the measure property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMEASURE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MEASURE }
     * 
     * 
     */
    public List<MEASURE> getMEASURE() {
        if (measure == null) {
            measure = new ArrayList<MEASURE>();
        }
        return this.measure;
    }

    /**
     * Gets the value of the qslink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qslink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQSLINK().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QSLINK }
     * 
     * 
     */
    public List<QSLINK> getQSLINK() {
        if (qslink == null) {
            qslink = new ArrayList<QSLINK>();
        }
        return this.qslink;
    }

    /**
     * Gets the value of the olink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the olink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOLINK().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OLINK }
     * 
     * 
     */
    public List<OLINK> getOLINK() {
        if (olink == null) {
            olink = new ArrayList<OLINK>();
        }
        return this.olink;
    }

    /**
     * Gets the value of the movelink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the movelink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMOVELINK().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MOVELINK }
     * 
     * 
     */
    public List<MOVELINK> getMOVELINK() {
        if (movelink == null) {
            movelink = new ArrayList<MOVELINK>();
        }
        return this.movelink;
    }

    /**
     * Gets the value of the measurelink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the measurelink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMEASURELINK().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MEASURELINK }
     * 
     * 
     */
    public List<MEASURELINK> getMEASURELINK() {
        if (measurelink == null) {
            measurelink = new ArrayList<MEASURELINK>();
        }
        return this.measurelink;
    }

    /**
     * Gets the value of the metalink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metalink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMETALINK().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link METALINK }
     * 
     * 
     */
    public List<METALINK> getMETALINK() {
        if (metalink == null) {
            metalink = new ArrayList<METALINK>();
        }
        return this.metalink;
    }

    /**
     * Gets the value of the cp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCP() {
        return cp;
    }

    /**
     * Sets the value of the cp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCP(String value) {
        this.cp = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURL() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURL(String value) {
        this.url = value;
    }

}
